controllers:
    resource: ../src/Controller/
    type: attribute

app_logout:
    path: /logout
    methods: GET

app_login:
    path: /auth/login
    controller: App\Controller\LoginController::index

